name: GunSmith
main: com.kraken.gunsmith.GunSmith
version: 1.9.4.1 (EpiCenter)
commands: 
     guns:
        description: Controls the GunSmith plugin, and opens a GUI for gun selection.
        usage: /<command> <argument>
     giveGun:
        description: Give GunSmith a gun.
        usage: /<command> <gunName/id>
     giveAmmo:
        description: Give GunSmith ammunition.
        usage: /<command> <ammoName> 
     giveArmor:
        description: Give GunSmith armor. (Not yet functional)
        usage: /<command> <ammoName> 
     giveGrenade:
        description: Give GunSmith grenades. (Not yet functional)
        usage: /<command> <ammoName>
permissions:
     gunsmith.*:
        description: Permission for all GunSmith commands.
        children:
           gunsmith.guns: true
           gunsmith.shoot: true
           gunsmith.craft: true
           gunsmith.explosives: true
           gunsmith.orbital: true
           gunsmith.give: true
     gunsmith.guns:
        description: Permission to use the GunSmith GUI.
     gunsmith.shoot:
        description: Permission to fire GunSmith weapons.
     gunsmith.craft:
        description: Permission to craft GunSmith custom recipes.
     gunsmith.explosives:
        description: Permission to use explosive GunSmith weapons (RPG).
     gunsmith.orbital:
        description: Permission to fire the orbital weapon from GunSmith.
     gunsmith.give:
        description: Perimission to give GunSmith weapons and ammo via command.